site_name: GeoInformatics 2026
docs_dir: markdown
site_dir: docs
base_url: https://geoinformatics-2026.netlify.app/

theme:
  name: null
  custom_dir: 'bulma/'
  # 404 page
  static_templates:
    - 404.html

extra_css:
  - css/nord_colors.css
  - css/colours.css
#  - css/bulma-carousel.min.css
#  - css/bulma-carousel-config.css
#extra_javascript:
#  - js/bulma-carousel.min.js
#  - js/bulma-carousel-script.js

#plugins:
#  - landing-preset:
#      name: catppuccin


nav:
- Home: index.md
- About: About.md
- Participation: Participation.md
- Program: Program.md
- Organisation: Organisation.md
- Venue: Venue.md
- Contact: Contact.md

watch:
  - bulma

#exclude_docs: |
#  index.md
